development:
  adapter: async

test:
  adapter: test

production:
  adapter: postgresql
  url: <%= ENV["DATABASE_URL"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  verify_ssl: false # Disable SSL verification for WebSocket connections
